id: IB3BFD2E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:29:51+00:00'
last_modified: '2022-06-08T05:21:03.211576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W18300
  title: རྟགས་འཇུག་གི་དགོངས་འགྲེལ་ཀེ་ཏ་ཀའི་གན་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4228':
      image_group_id: I1KG14889
      title: Volume 1 of rtags 'jug gi dgongs 'grel ke ta ka'i gan mdzod
      total_pages: 74
      order: 1
      base_file: 4228.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
